spring:
#  profiles: dev
  config:
    activate:
      on-profile: dev

#  profiles:
#    dev:
#      enavled: false
#      ip: 192.168.1.100
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

init:
  setting: false

#  jdbc:h2:~/jpashop
#  jdbc:h2:tcp://localhost/~/querydsl
#   jdbc:h2:tcp://localhost/~/jpashop